import { generateTailWindStrings } from 'lib/utils';

const styles = {
    container: [
        'bg-white',
        'border',
        'border-gray-200',
        'cursor-pointer',
        'flex',
        'flex-col',
        'group',
        'hover:-translate-y-1',
        'hover:border-violet-300',
        'hover:shadow-xl',
        'lg:w-2/5',
        'md:w-full',
        'mx-1',
        'my-4',
        'px-10',
        'py-8',
        'rounded-2xl',
        'shadow-md',
        'transition-all',
        'duration-300',
    ],
    title: [
        'font-bold',
        'group-hover:text-violet-900',
        'leading-snug',
        'mt-2',
        'pb-3',
        'text-2xl',
        'transition-colors',
        'duration-200',
    ],
    date: [
        'mb-3',
        'text-gray-400',
        'text-xs',
        'tracking-widest',
        'uppercase',
    ],
    metaData: [
        'border-t',
        'border-gray-100',
        'pt-3',
        'pb-4',
        'text-gray-500',
        'text-sm',
        'leading-relaxed',
    ],
    readMore: [
        'flex',
        'flex-row',
        'font-medium',
        'gap-1',
        'items-center',
        'mb-4',
        'text-violet-700',
        'hover:text-violet-900',
        'transition-colors',
    ]
};

export default generateTailWindStrings(styles);